### ISSUE TITLE
Nodes created on wrong stack

### ISSUE THREAD

**Issue by montegoulding** [matthewmaier/howstr#1]
The function `makeNode` calls [`create field`](https://github.com/matthewmaier/howstr/blob/master/Howstr_Beta/software/displayerang.livecode#L532) but does not specify a group to create the field in or ensure `the defaultStack` to ensure the objects are created on the correct stack. The change to using script libraries has probably injected a bug where the defaultStack is not the main Howstr stack.

**Comment by matthewmaier** [comment]
Fixed a ton of little things like that created by moving more code to script-only stacks. Seems to all work now.
